src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->getEmail();
    }
}

src/Controller/EcommerceController.php
<?php

namespace App\Controller;

use App\Repository\ProduitRepository;
use App\Repository\CommandeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EcommerceController extends AbstractController
{
    #[Route('/', name: 'app_ecommerce')]
    public function index(ProduitRepository $repo): Response
    {
        $produits = $repo->findAll();
        return $this->render('ecommerce/index.html.twig', [
            'produits'=> $produits,
        ]);
    }
    #[Route('/show/{id}', name: 'app_show')]
    public function show(ProduitRepository $repo, $id, RequestStack $rs)
    {
        $produit = $repo->find($id);
        $session = $rs->getSession();
        $cart = $session->get('cart', []);
        if(!empty($cart[$id]))
        {
            $cartquantite = $cart[$id];
            $stock = $produit->getStock();
            $encore= $stock - $cartquantite;
        }
        else{
            $encore = $produit->getStock();
        }
        return $this->render('ecommerce/show.html.twig',[
            'produit' => $produit,
            "maxQuantite" => $encore,
        ]);
    }
    #[Route('/profil' , name:"app_profil" )]
    public function profil(CommandeRepository $repo)
    {
        $commandes = $repo->findAll();


        return $this->render('ecommerce/profil.html.twig', [
            'commandes' => $commandes
        ]);
    }
}

templates/ecommerce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

<div class="card border-light mt-3 mb-5 ">
<div class="card-body">
<h2 class="text-center mt-2 mb-2">Bienvenue {% if app.user %}{{app.user.pseudo}}, que vas-tu hachetter aujourd'hui ?{% else %}
  sur Hachette {% endif %}</h2>
  </div>
  </div>

<div class="container-fluid text-center mt-4 card border-primary"style=" min-height: 80vh;"> 
<div class="row justify-content-md-between p-4">
{% for item in produits %}
    {% if item.stock > 0 %}
    
    <div id="responsive" class="card text-white col-md-3 mx-2 my-1 border-primary ">
    <div class="card-header text-center"> {{ item.titre }} </div>
    <div class="card-body text-center">
        
        <img class="text-center img-fluid" src="{{ item.photo }}" alt="" >
        <hr>
        <p>Prix : {{ item.prix }} €</p>

        <a href="{{path('app_show', {id: item.id})}}" class="btn btn-dark col-md-auto"> Commander</a>
    </div>
    </div>
    {% endif %}
{% endfor %}
</div>
</div>


{% endblock %}

templates/ecommerce/profil.html.twig
{% extends 'security.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
<h1>Mon profil</h1>

<div class="card border-dark mx-auto mb-5" style="max-width: 60vw;">
            <div class="card-header"> <h3>{{app.user.Pseudo}}</h3></div>
            <div class="card-body container">
            <div class="row">
            <h4 class="card-title col-md-12">Vos informations</h4>
                <br><hr><br>
                <h4 class="subtitle col-md-6">Nom : {{app.user.nom}}</h4>
                <h4 class="subtitle col-md-6">Prenom : {{app.user.prenom}}</h4>
                
                <h4 id="responsive" class="col-md-6 subtitle">Email : {{app.user.email}}</h4>
                <h4 class="col-md-6 subtitle">Civilité : {{app.user.civilite}}</h4>            
                

            </div>
            </div>
            <div class="container">
                <div class="row">
                <div class="col-md-10"></div>
                    <div class="col-md-auto"><a href="#" class="btn btn-primary">Modifier son Compte</a></div>
                </div>
            </div>
        </div>

<h2>Mes commandes</h2>
{% set date = "" %}
{% set NewTotal = 0 %}
{% for commande in commandes %}

{% if commande.Membre.id == app.user.id %}
{% set dateTemp = commande.dateEnregistrement|date("d/m/y à H:i:s") %}
{% if date == dateTemp and date != "" %}
    <hr>
    <h4 class="card-title">{{commande.produit.titre}}</h4>
                <p class="card-text">
                quantité : {{commande.quantite}}
                </p>
                <div class="container">
                    <div class="row">
                        <div class="col-md-10">Etat de la commande : {{commande.etat}}</div>
                        <div class="col-md-auto"><h5>Prix Total : {{ commande.montant }}€</h5></div>
                    </div>
                </div>
    {% set total = total + commande.montant %}           
    {% set  NewTotal = total  %}
    

{% elseif date == "" %}
<div class="card border-primary mb-3" style="max-width: 80vw;">
            <div class="card-header"><h3>Commande du {{commande.dateEnregistrement|date("d/m/y à H:i:s")}}</h3></div>
            <div class="card-body">
                <h4 class="card-title">{{commande.produit.titre}}</h4>
                <p class="card-text">
                quantité : {{commande.quantite}}
                </p>
                <div class="container">
                    <div class="row">
                        <div class="col-md-10">Etat de la commande : {{commande.etat}}</div>
                        <div class="col-md-auto"><h5>Prix Total : {{ commande.montant }}€</h5></div>
                    </div>
                </div>
{% set total = commande.montant %}


{% else %}
{% if NewTotal != 0 %}<h1>Prix Total de la commande : {{NewTotal}}€</h1>{% set NewTotal = 0  %} {% set total = 0  %}{% endif %}
</div></div>
<div class="card border-primary mb-3" style="max-width: 80vw;">
            <div class="card-header"><h3>Commande du {{commande.dateEnregistrement|date("d/m/y à H:i:s")}}</h3></div>
            <div class="card-body">
                <h4 class="card-title">{{commande.produit.titre}}</h4>
                <p class="card-text">
                quantité : {{commande.quantite}}
                </p>
                <div class="container">
                    <div class="row">
                        <div class="col-md-10">Etat de la commande : {{commande.etat}}</div>
                        <div class="col-md-auto"><h5>Prix Total : {{ commande.montant }}€</h5></div>
                    </div>
                </div>
{% set total = commande.montant %}
{% endif %}

{% set date = commande.dateEnregistrement|date("d/m/y à H:i:s") %}
{% endif %}

    
{% endfor %}
{% if NewTotal != 0 %}<h1>Prix Total de la commande : {{NewTotal}}€</h1>{% endif %}
</div></div>







{% endblock %}

templates/ecommerce/show.html.twig
{% extends 'security.html.twig' %}

{% block title %}produit{% endblock %}

{% block body %}
<div class="card border-light mt-5 mb-3 f-s-4">
  <h3 class="card-header"> {{ produit.titre }} </h3>
  <h4 class="card-title text-center"> {{ produit.taille }} / {{ produit.collection }}</h4>
  
  <div class="text-center">
    <img src="{{ produit.photo }}" alt="" class="img-fluide">
    <h5 class="card-title text-muted"> Couleur : {{ produit.couleur }}</h5>
  </div>
   
    
  <div class="card-body">
  <p class="card-header"> Description : </p>
    <p class="card-text"> {{ produit.description }} </p>
  </div>
  <div class="container">
  <div class="row justify-content-between">
  <div class="card-footer col-md-3 text-muted text-center">
    (Ecrit le {{ produit.dateenregistrement|date("d/m/Y à H:i:s") }})
  </div>
  <h5 class="card-title col-md-3"> Prix : {{ produit.prix }} € </h5>
</div></div></div>

<form method="POST" action="{{ path('cart_add', {id: produit.id }) }}" class="form-inline d-inline-block" >
	<input type="number" name="addQuantite" class="form-control mr-2" max="{{maxQuantite}}" min="1" value="1">
	<button type="submit" class="btn btn-dark" > Ajouter au panier</button>
</form>

{% endblock %}